/******************************************************************************/
/*            Generated by IBExpert 2018.8.3.1 24.09.2018 17:10:50            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'fbembed.dll';

CREATE DATABASE 'db\shrfs.fdb'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CONTRAGENTS (
    CODE  VARCHAR(10) NOT NULL,
    NAME  VARCHAR(100)
);

CREATE TABLE SESSIONS (
    SESSIONNUM     INTEGER NOT NULL,
    STARTDATETIME  TIMESTAMP NOT NULL,
    ENDDATETIME    TIMESTAMP NOT NULL,
    USERNAME       VARCHAR(50)
);

CREATE TABLE STATIONS (
    CODE  VARCHAR(10) NOT NULL,
    NAME  VARCHAR(50)
);

CREATE TABLE STORAGES (
    CODE  VARCHAR(10) NOT NULL,
    NAME  VARCHAR(50)
);

CREATE TABLE TANKS (
    SESSIONNUM     INTEGER NOT NULL,
    STARTDATETIME  TIMESTAMP NOT NULL,
    TANKNUM        VARCHAR(10) NOT NULL,
    ENDDENSITY     DOUBLE PRECISION NOT NULL
);

CREATE TABLE WARES (
    CODE  VARCHAR(11) NOT NULL,
    NAME  VARCHAR(100)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CONTRAGENTS ADD CONSTRAINT PK_CONTRAGENTS PRIMARY KEY (CODE);
ALTER TABLE SESSIONS ADD CONSTRAINT PK_SESSIONS PRIMARY KEY (SESSIONNUM, STARTDATETIME);
ALTER TABLE STATIONS ADD CONSTRAINT PK_STATIONS PRIMARY KEY (CODE);
ALTER TABLE STORAGES ADD CONSTRAINT PK_STORAGES PRIMARY KEY (CODE);
ALTER TABLE WARES ADD CONSTRAINT PK_WARES PRIMARY KEY (CODE);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE TANKS ADD CONSTRAINT FK_TANKS_1 FOREIGN KEY (SESSIONNUM, STARTDATETIME) REFERENCES SESSIONS (SESSIONNUM, STARTDATETIME);
